apiVersion: v1
kind: Service
metadata:
  name: testcase
  namespace: argocd-neweks132-6a5mw
  labels:
    app: testcase
spec:
  type: ClusterIP
  selector:
    app: testcase
  ports:
    - name: https
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testcase
  namespace: argocd-neweks132-6a5mw
  labels:
    app: testcase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testcase
  template:
    metadata:
      labels:
        app: testcase
    spec:
      containers:
        - name: testcase-container
          image: satyamp07/waitlist:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 512Mi
              cpu: 200m
            limits:
              memory: 1024Mi
              cpu: 400m
          env:
            - name: NODE_ENV
              value: production
            - name: NEXT_PUBLIC_ATLAS_BACKEND
              value: https://api.atlas.scoutflo.com/api
      imagePullSecrets:
        - name: scoutflo-satyam-docker-new-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testcase
  namespace: argocd-neweks132-6a5mw
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: waitlist-ryjwv.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: testcase
                port:
                  number: 3000
  tls:
    - hosts:
        - waitlist-ryjwv.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
