apiVersion: v1
kind: Service
metadata:
  name: lol-5-splph
  namespace: default
  labels:
    app: lol-5-splph
spec:
  type: ClusterIP
  selector:
    app: lol-5-splph
  ports:
    - name: https
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lol-5-splph
  namespace: default
  labels:
    app: lol-5-splph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lol-5-splph
  template:
    metadata:
      labels:
        app: lol-5-splph
    spec:
      containers:
        - name: lol-5-splph-container
          image: satyamp07/waitlist:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 200m
          env:
            - name: NEXT_PUBLIC_ATLAS_BACKEND
              value: https://api.atlas.scoutflo.com/api
      imagePullSecrets:
        - name: scoutflo-satyam-docker-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lol-5-splph
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: lol-5-sdsxg3-rhxa6kb6ufgplydj-uhhx2.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lol-5-splph
                port:
                  number: 3000
    - host: test5.kubedeploy.live
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lol-5-splph
                port:
                  number: 3000
  tls:
    - hosts:
        - lol-5-sdsxg3-rhxa6kb6ufgplydj-uhhx2.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
    - hosts:
        - test5.kubedeploy.live
      secretName: wildcard-z0036500rviu1vgw63pe-tls
