apiVersion: v1
kind: Service
metadata:
  name: validchecks1
  namespace: default
  labels:
    app: validchecks1
spec:
  type: ClusterIP
  selector:
    app: validchecks1
  ports:
    - name: https
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validchecks1
  namespace: default
  labels:
    app: validchecks1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validchecks1
  template:
    metadata:
      labels:
        app: validchecks1
    spec:
      containers:
        - name: validchecks1-container
          image: satyam07/waitlist:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 500m
          env:
            - name: NODE_ENV
              value: production
            - name: node
              value: 1.22.22
      imagePullSecrets:
        - name: scoutflo-satyam-docker-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: validchecks1
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: waitlist-g6tfm.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: validchecks1
                port:
                  number: 3000
  tls:
    - hosts:
        - waitlist-g6tfm.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
