apiVersion: v1
kind: Service
metadata:
  name: atharvadeploytesting12
  namespace: default
  labels:
    app: atharvadeploytesting12
spec:
  type: ClusterIP
  selector:
    app: atharvadeploytesting12
  ports:
    - name: tcp
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atharvadeploytesting12
  namespace: default
  labels:
    app: atharvadeploytesting12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atharvadeploytesting12
  template:
    metadata:
      labels:
        app: atharvadeploytesting12
    spec:
      containers:
        - name: atharvadeploytesting12-container
          image: 891376929531.dkr.ecr.ap-south-1.amazonaws.com/cost-analyzer-atharva1889-tfucl:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 500m
          env:
            - name: NODE_ENV
              value: production
      imagePullSecrets:
        - name: scoutflo-ecr-test-aws-ecr

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atharvadeploytesting12
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: atharva-ecr-test-2-kotok.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: atharvadeploytesting12
                port:
                  number: 80
  tls:
    - hosts:
        - atharva-ecr-test-2-kotok.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
