apiVersion: v1
kind: Service
metadata:
  name: dfefvwrvwrtvwtr
  namespace: default
  labels:
    app: dfefvwrvwrtvwtr
spec:
  type: ClusterIP
  selector:
    app: dfefvwrvwrtvwtr
  ports:
    - name: https
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dfefvwrvwrtvwtr
  namespace: default
  labels:
    app: dfefvwrvwrtvwtr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfefvwrvwrtvwtr
  template:
    metadata:
      labels:
        app: dfefvwrvwrtvwtr
    spec:
      containers:
        - name: dfefvwrvwrtvwtr-container
          image: satyamp07/waitlist:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 500m
          env:
            - name: NODE_ENV
              value: production
            - name: NEXT_PUBLIC_ATLAS_BACKEND
              value: https://api.atlas.scoutflo.com/api
      imagePullSecrets:
        - name: scoutflo-satyam-docker-latest-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dfefvwrvwrtvwtr
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: waitlist2-uasrl.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dfefvwrvwrtvwtr
                port:
                  number: 3000
  tls:
    - hosts:
        - waitlist2-uasrl.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
