apiVersion: v1
kind: Service
metadata:
  name: dev-service-1-pf-cj
  namespace: default
  labels:
    app: dev-service-1-pf-cj
spec:
  type: ClusterIP
  selector:
    app: dev-service-1-pf-cj
  ports:
    - name: https
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-service-1-pf-cj
  namespace: default
  labels:
    app: dev-service-1-pf-cj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-service-1-pf-cj
  template:
    metadata:
      labels:
        app: dev-service-1-pf-cj
    spec:
      containers:
        - name: dev-service-1-pf-cj-container
          image: satyamp07/waitlist:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 200m
          env: []
      imagePullSecrets:
        - name: scoutflo-satyam-docker-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-service-1-pf-cj
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: dev-service-1-sdsaw9cth5djvj-jaolf4khz-p5ojr.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dev-service-1-pf-cj
                port:
                  number: 3000
  tls:
    - hosts:
        - dev-service-1-sdsaw9cth5djvj-jaolf4khz-p5ojr.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
