apiVersion: v1
kind: ServiceAccount
metadata:
  name: scoutflo-sa-qaweryu
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::891376929531:role/Scoutflo-cloud-credentials-3272ca00-3b68-4272-8e2d-90327b6c3965

---
apiVersion: v1
kind: Service
metadata:
  name: qaweryu
  namespace: kube-system
  labels:
    app: qaweryu
spec:
  type: ClusterIP
  selector:
    app: qaweryu
  ports:
    - name: https
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qaweryu
  namespace: kube-system
  labels:
    app: qaweryu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qaweryu
  template:
    metadata:
      labels:
        app: qaweryu
    spec:
      serviceAccountName: scoutflo-sa-qaweryu
      containers:
        - name: qaweryu-container
          image: 891376929531.dkr.ecr.ap-south-2.amazonaws.com/waitlist-private:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 500m
          env:
            - name: NEXT_PUBLIC_ATLAS_BACKEND
              value: https://api.atlas.scoutflo.com/api

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qaweryu
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: kalpesh.scoutflo.services
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qaweryu
                port:
                  number: 3000
    - host: waitlistfinal-2zmni.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qaweryu
                port:
                  number: 3000
  tls:
    - hosts:
        - waitlistfinal-2zmni.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
    - hosts:
        - kalpesh.scoutflo.services
      secretName: wildcard-z06448543vcs2ukhgxk1w-tls
