apiVersion: v1
kind: Service
metadata:
  name: n8n-service-1-fiecw
  namespace: default
  labels:
    app: n8n-service-1-fiecw
spec:
  type: ClusterIP
  selector:
    app: n8n-service-1-fiecw
  ports:
    - name: https
      protocol: TCP
      port: 5678
      targetPort: 5678

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-service-1-fiecw
  namespace: default
  labels:
    app: n8n-service-1-fiecw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n-service-1-fiecw
  template:
    metadata:
      labels:
        app: n8n-service-1-fiecw
    spec:
      containers:
        - name: n8n-service-1-fiecw-container
          image: satyamp07/n8n:1.76.1
          ports:
            - containerPort: 5678
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 200m
          env: []
      imagePullSecrets:
        - name: scoutflo-satyam-docker-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-service-1-fiecw
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: n8n-service-1-sdsktbmvifeoniyv7f-zvebu-jfxwd.scoutflo.agency
      http:
        paths:
          - path: /new
            pathType: Prefix
            backend:
              service:
                name: n8n-service-1-fiecw
                port:
                  number: 5678
  tls:
    - hosts:
        - n8n-service-1-sdsktbmvifeoniyv7f-zvebu-jfxwd.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
