apiVersion: v1
kind: Service
metadata:
  name: validchecks8
  namespace: default
  labels:
    app: validchecks8
spec:
  type: ClusterIP
  selector:
    app: validchecks8
  ports:
    - name: https
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validchecks8
  namespace: default
  labels:
    app: validchecks8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validchecks8
  template:
    metadata:
      labels:
        app: validchecks8
    spec:
      containers:
        - name: validchecks8-container
          image: satyamp07/waitlist:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 500m
          env:
            - name: NODE_ENV
              value: production
            - name: Atharva
              value: Test
      imagePullSecrets:
        - name: scoutflo-satyam-docker-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: validchecks8
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: validchecks4-kbnyn.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: validchecks8
                port:
                  number: 3000
  tls:
    - hosts:
        - validchecks4-kbnyn.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
