apiVersion: v1
kind: ServiceAccount
metadata:
  name: scoutflo-sa-tlsprodtest7
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::891376929531:role/Scoutflo-cloud-credentials-707e0197-a28b-4066-8090-d123c0ed386e

---
apiVersion: v1
kind: Service
metadata:
  name: tlsprodtest7
  namespace: default
  labels:
    app: tlsprodtest7
spec:
  type: ClusterIP
  selector:
    app: tlsprodtest7
  ports:
    - name: https
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tlsprodtest7
  namespace: default
  labels:
    app: tlsprodtest7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tlsprodtest7
  template:
    metadata:
      labels:
        app: tlsprodtest7
    spec:
      serviceAccountName: scoutflo-sa-tlsprodtest7
      containers:
        - name: tlsprodtest7-container
          image: 891376929531.dkr.ecr.ap-south-2.amazonaws.com/waitlist-private:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 500m
          env:
            - name: NEXT_PUBLIC_ATLAS_BACKEND
              value: https://api.atlas.scoutflo.com/api

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tlsprodtest7
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: atharvaproduction.rkjangidbuilder.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tlsprodtest7
                port:
                  number: 3000
    - host: domaincheck-ldfb2.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tlsprodtest7
                port:
                  number: 3000
  tls:
    - hosts:
        - domaincheck-ldfb2.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
    - hosts:
        - atharvaproduction.rkjangidbuilder.com
      secretName: wildcard-z07004282wlzt96eag2kr-tls
