apiVersion: v1
kind: Service
metadata:
  name: linkcheck
  namespace: default
  labels:
    app: linkcheck
spec:
  type: ClusterIP
  selector:
    app: linkcheck
  ports:
    - name: https
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkcheck
  namespace: default
  labels:
    app: linkcheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkcheck
  template:
    metadata:
      labels:
        app: linkcheck
    spec:
      containers:
        - name: linkcheck-container
          image: satyamp07/waitlist:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 500m
          env:
            - name: NEXT_PUBLIC_ATLAS_BACKEND
              value: https://api.atlas.scoutflo.com/api
      imagePullSecrets:
        - name: scoutflo-satyam-docker-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linkcheck
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: waitlist-service-uwkzu.scoutflo.agency
      http:
        paths:
          - path: /athu
            pathType: Prefix
            backend:
              service:
                name: linkcheck
                port:
                  number: 3000
  tls:
    - hosts:
        - waitlist-service-uwkzu.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
