apiVersion: v1
kind: Service
metadata:
  name: judge0-boardinfinity
  namespace: default
  labels:
    app: judge0-boardinfinity
spec:
  type: ClusterIP
  selector:
    app: judge0-boardinfinity
  ports:
    - name: https
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge0-boardinfinity
  namespace: default
  labels:
    app: judge0-boardinfinity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge0-boardinfinity
  template:
    metadata:
      labels:
        app: judge0-boardinfinity
    spec:
      containers:
        - name: judge0-boardinfinity-container
          image: kalpeshbhalekar/judge0:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 1024Mi
              cpu: 200m
            limits:
              memory: 2048Mi
              cpu: 400m
          env:
            - name: NODE_ENV
              value: production
      imagePullSecrets:
        - name: scoutflo-kalpesh-docker-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: judge0-boardinfinity
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: judge0-uw7q7.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: judge0-boardinfinity
                port:
                  number: 80
  tls:
    - hosts:
        - judge0-uw7q7.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
