apiVersion: v1
kind: ServiceAccount
metadata:
  name: scoutflo-sa-freetrialservicedeploy1assd
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::891376929531:role/Scoutflo-cloud-credentials-707e0197-a28b-4066-8090-d123c0ed386e

---
apiVersion: v1
kind: Service
metadata:
  name: freetrialservicedeploy1assd
  namespace: default
  labels:
    app: freetrialservicedeploy1assd
spec:
  type: ClusterIP
  selector:
    app: freetrialservicedeploy1assd
  ports:
    - name: https
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freetrialservicedeploy1assd
  namespace: default
  labels:
    app: freetrialservicedeploy1assd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freetrialservicedeploy1assd
  template:
    metadata:
      labels:
        app: freetrialservicedeploy1assd
    spec:
      serviceAccountName: scoutflo-sa-freetrialservicedeploy1assd
      containers:
        - name: freetrialservicedeploy1assd-container
          image: 891376929531.dkr.ecr.ap-south-2.amazonaws.com/waitlist-private:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 512Mi
              cpu: 200m
            limits:
              memory: 1024Mi
              cpu: 400m
          env:
            - name: NEXT_PUBLIC_ATLAS_BACKEND
              value: https://api.atlas.scoutflo.com/api

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freetrialservicedeploy1assd
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: waitlistother-rbhmp.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: freetrialservicedeploy1assd
                port:
                  number: 3000
  tls:
    - hosts:
        - waitlistother-rbhmp.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
