apiVersion: v1
kind: Service
metadata:
  name: validchecks10
  namespace: default
  labels:
    app: validchecks10
spec:
  type: ClusterIP
  selector:
    app: validchecks10
  ports:
    - name: https
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validchecks10
  namespace: default
  labels:
    app: validchecks10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validchecks10
  template:
    metadata:
      labels:
        app: validchecks10
    spec:
      containers:
        - name: validchecks10-container
          image: satyamp07/waitlist:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 64Mi
              cpu: 200m
            limits:
              memory: 1024Mi
              cpu: 300m
          env:
            - name: NODE_ENV
              value: production
            - name: Atharva
              value: Test
      imagePullSecrets:
        - name: scoutflo-satyam-docker-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: validchecks10
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: validchecks5-hysj.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: validchecks10
                port:
                  number: 80
  tls:
    - hosts:
        - validchecks5-hysj.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
