apiVersion: v1
kind: Service
metadata:
  name: Judge0Test
  namespace: default
  labels:
    app: Judge0Test
spec:
  type: ClusterIP
  selector:
    app: Judge0Test
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Judge0Test
  namespace: default
  labels:
    app: Judge0Test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Judge0Test
  template:
    metadata:
      labels:
        app: Judge0Test
    spec:
      containers:
        - name: Judge0Test-container
          image: satyamp07/judge0-server:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 1Gi
              cpu: 1000m
          env: []
      imagePullSecrets:
        - name: scoutflo-satyam-judge0-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: Judge0Test
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: judge0-test-klssn.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: Judge0Test
                port:
                  number: 80
  tls:
    - hosts:
        - judge0-test-klssn.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
