apiVersion: v1
kind: Service
metadata:
  name: phpadminatharva
  namespace: default
  labels:
    app: phpadminatharva
spec:
  type: ClusterIP
  selector:
    app: phpadminatharva
  ports:
    - name: https
      protocol: TCP
      port: 9000
      targetPort: 9000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpadminatharva
  namespace: default
  labels:
    app: phpadminatharva
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpadminatharva
  template:
    metadata:
      labels:
        app: phpadminatharva
    spec:
      containers:
        - name: phpadminatharva-container
          image: kalpeshbhalekar/phpmyadmin:latest
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 500m
          env:
            - name: NODE_ENV
              value: production
      imagePullSecrets:
        - name: scoutflo-kalpesh-docker-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phpadminatharva
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: phpadmin-ov1rr.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: phpadminatharva
                port:
                  number: 9000
  tls:
    - hosts:
        - phpadmin-ov1rr.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
