apiVersion: v1
kind: ServiceAccount
metadata:
  name: scoutflo-sa-testnamespacehjj
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::891376929531:role/Scoutflo-cloud-credentials-4d65ad8d-e374-4005-8970-1bb545f57232

---
apiVersion: v1
kind: Service
metadata:
  name: testnamespacehjj
  namespace: default
  labels:
    app: testnamespacehjj
spec:
  type: ClusterIP
  selector:
    app: testnamespacehjj
  ports:
    - name: https
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testnamespacehjj
  namespace: default
  labels:
    app: testnamespacehjj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testnamespacehjj
  template:
    metadata:
      labels:
        app: testnamespacehjj
    spec:
      serviceAccountName: scoutflo-sa-testnamespacehjj
      containers:
        - name: testnamespacehjj-container
          image: 891376929531.dkr.ecr.ap-south-2.amazonaws.com/waitlist-private:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 500m
          env:
            - name: NEXT_PUBLIC_ATLAS_BACKEND
              value: https://api.atlas.scoutflo.com/api

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testnamespacehjj
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: waitlist-8-hpr.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: testnamespacehjj
                port:
                  number: 3000
  tls:
    - hosts:
        - waitlist-8-hpr.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
