apiVersion: v1
kind: ServiceAccount
metadata:
  name: scoutflo-sa-validchecks9
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::891376929531:role/Scoutflo-cloud-credentials-3272ca00-3b68-4272-8e2d-90327b6c3965

---
apiVersion: v1
kind: Service
metadata:
  name: validchecks9
  namespace: default
  labels:
    app: validchecks9
spec:
  type: ClusterIP
  selector:
    app: validchecks9
  ports:
    - name: https
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validchecks9
  namespace: default
  labels:
    app: validchecks9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validchecks9
  template:
    metadata:
      labels:
        app: validchecks9
    spec:
      serviceAccountName: scoutflo-sa-validchecks9
      containers:
        - name: validchecks9-container
          image: 891376929531.dkr.ecr.ap-south-1.amazonaws.com/atlantis-croskaoas-7lkr:5.4.0
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 500m
          env:
            - name: NODE_ENV
              value: production

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: validchecks9
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: atharva-ecr-test-5-c6iml.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: validchecks9
                port:
                  number: 80
  tls:
    - hosts:
        - atharva-ecr-test-5-c6iml.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
