apiVersion: v1
kind: ServiceAccount
metadata:
  name: scoutflo-sa-test1
  namespace: details-ln591
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::891376929531:role/Scoutflo-cloud-credentials-3272ca00-3b68-4272-8e2d-90327b6c3965

---
apiVersion: v1
kind: Service
metadata:
  name: test1
  namespace: details-ln591
  labels:
    app: test1
spec:
  type: ClusterIP
  selector:
    app: test1
  ports:
    - name: https
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
  namespace: details-ln591
  labels:
    app: test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test1
  template:
    metadata:
      labels:
        app: test1
    spec:
      serviceAccountName: scoutflo-sa-test1
      containers:
        - name: test1-container
          image: 891376929531.dkr.ecr.ap-south-2.amazonaws.com/waitlist-private:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 500m
          env:
            - name: NEXT_PUBLIC_ATLAS_BACKEND
              value: https://api.atlas.scoutflo.com/api

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test1
  namespace: details-ln591
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: abcd.scoutflo.com
      http:
        paths:
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: test1
                port:
                  number: 3000
    - host: waitlistenvs-gocb4.scoutflo.agency
      http:
        paths:
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: test1
                port:
                  number: 3000
  tls:
    - hosts:
        - waitlistenvs-gocb4.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
