apiVersion: v1
kind: Service
metadata:
  name: service-2-cfad
  namespace: default
  labels:
    app: service-2-cfad
spec:
  type: ClusterIP
  selector:
    app: service-2-cfad
  ports:
    - name: https
      protocol: TCP
      port: 5678
      targetPort: 5678

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-2-cfad
  namespace: default
  labels:
    app: service-2-cfad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-2-cfad
  template:
    metadata:
      labels:
        app: service-2-cfad
    spec:
      containers:
        - name: service-2-cfad-container
          image: satyamp07/waitlist:latest
          ports:
            - containerPort: 5678
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 200m
          env: []
      imagePullSecrets:
        - name: scoutflo-satyam-docker-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-2-cfad
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: service-2-sdsqzhhkuwdcl1ci-pxsh2v8-glrhi.scoutflo.agency
      http:
        paths:
          - path: /new
            pathType: Prefix
            backend:
              service:
                name: service-2-cfad
                port:
                  number: 5678
  tls:
    - hosts:
        - service-2-sdsqzhhkuwdcl1ci-pxsh2v8-glrhi.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
