apiVersion: v1
kind: Service
metadata:
  name: atharvadeploytesting20
  namespace: default
  labels:
    app: atharvadeploytesting20
spec:
  type: ClusterIP
  selector:
    app: atharvadeploytesting20
  ports:
    - name: https
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atharvadeploytesting20
  namespace: default
  labels:
    app: atharvadeploytesting20
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atharvadeploytesting20
  template:
    metadata:
      labels:
        app: atharvadeploytesting20
    spec:
      containers:
        - name: atharvadeploytesting20-container
          image: 891376929531.dkr.ecr.ap-south-1.amazonaws.com/cost-analyzer-chitest-z2wtd:2.3.4-e5ad606
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 512Mi
              cpu: 200m
            limits:
              memory: 1024Mi
              cpu: 400m
          env:
            - name: NODE_ENV
              value: production
      imagePullSecrets:
        - name: scoutflo-ecr-test-aws-ecr

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atharvadeploytesting20
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: atharva-ecr-test-adrhz.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: atharvadeploytesting20
                port:
                  number: 80
  tls:
    - hosts:
        - atharva-ecr-test-adrhz.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
