apiVersion: v1
kind: Service
metadata:
  name: cservice-2-b8nts
  namespace: default
  labels:
    app: cservice-2-b8nts
spec:
  type: ClusterIP
  selector:
    app: cservice-2-b8nts
  ports:
    - name: https
      protocol: TCP
      port: 5678
      targetPort: 5678

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cservice-2-b8nts
  namespace: default
  labels:
    app: cservice-2-b8nts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cservice-2-b8nts
  template:
    metadata:
      labels:
        app: cservice-2-b8nts
    spec:
      containers:
        - name: cservice-2-b8nts-container
          image: satyamp07/n8n:latest
          ports:
            - containerPort: 5678
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 200m
          env: []
      imagePullSecrets:
        - name: scoutflo-satyam-docker-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cservice-2-b8nts
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: cservice-2-sdscqqzpj6gaoy00wnphdcg2-olnyi.scoutflo.agency
      http:
        paths:
          - path: /new
            pathType: Prefix
            backend:
              service:
                name: cservice-2-b8nts
                port:
                  number: 5678
    - host: test2.udichi.agency
      http:
        paths:
          - path: /new
            pathType: Prefix
            backend:
              service:
                name: cservice-2-b8nts
                port:
                  number: 5678
  tls:
    - hosts:
        - cservice-2-sdscqqzpj6gaoy00wnphdcg2-olnyi.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
    - hosts:
        - test2.udichi.agency
      secretName: wildcard-z03233141hyez4y5qyk84-tls
