# Service for the server
apiVersion: v1
kind: Service
metadata:
  name: judge0-server
  namespace: default
spec:
  selector:
    app: judge0
    component: server
  ports:
    - protocol: TCP
      port: 2358
      targetPort: 2358
  type: ClusterIP

---
# Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge0-server
  namespace: default
  labels:
    app: judge0
    component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge0
      component: server
  template:
    metadata:
      labels:
        app: judge0
        component: server
    spec:
      containers:
        - name: server
          image: satyamp07/judge0:latest
          command: ["/bin/bash"]
          args: ["-c", "rails db:migrate && rails server"]
          ports:
            - containerPort: 2358
          resources:
            requests:
              memory: 512Mi
              cpu: 200m
            limits:
              memory: 1024Mi
              cpu: 400m
          env:
            - name: NEXT_PUBLIC_ATLAS_BACKEND
              value: https://api.atlas.scoutflo.com/api
            # Add all your judge0.conf environment variables here
            - name: RAILS_ENV
              value: "production"
            - name: RAILS_MAX_THREADS
              value: "16"
            - name: INTERVAL
              value: "0.1"
            # Add other environment variables as needed
      imagePullSecrets:
        - name: scoutflo-satyam-docker-docker

---
# Worker Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge0-worker
  namespace: default
  labels:
    app: judge0
    component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge0
      component: worker
  template:
    metadata:
      labels:
        app: judge0
        component: worker
    spec:
      containers:
        - name: worker
          image: satyamp07/judge0:latest
          command: ["./scripts/workers"]
          resources:
            requests:
              memory: 512Mi
              cpu: 200m
            limits:
              memory: 1024Mi
              cpu: 400m
          env:
            - name: RAILS_ENV
              value: "production"
            - name: RAILS_MAX_THREADS
              value: "16"
            - name: INTERVAL
              value: "0.1"
      imagePullSecrets:
        - name: scoutflo-satyam-docker-docker
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: judge0ab4
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: judge0-main-ip03n.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: judge0ab4
                port:
                  number: 3000
  tls:
    - hosts:
        - judge0-main-ip03n.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
