apiVersion: v1
kind: ServiceAccount
metadata:
  name: scoutflo-sa-domaintest9
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::891376929531:role/Scoutflo-cloud-credentials-6c7ecb39-eb5c-4902-a3ea-da679ef998ec

---
apiVersion: v1
kind: Service
metadata:
  name: domaintest9
  namespace: default
  labels:
    app: domaintest9
spec:
  type: ClusterIP
  selector:
    app: domaintest9
  ports:
    - name: https
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: domaintest9
  namespace: default
  labels:
    app: domaintest9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: domaintest9
  template:
    metadata:
      labels:
        app: domaintest9
    spec:
      serviceAccountName: scoutflo-sa-domaintest9
      containers:
        - name: domaintest9-container
          image: 891376929531.dkr.ecr.ap-south-2.amazonaws.com/waitlist-private:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 512Mi
              cpu: 200m
            limits:
              memory: 1024Mi
              cpu: 400m
          env:
            - name: NEXT_PUBLIC_ATLAS_BACKEND
              value: https://api.atlas.scoutflo.com/api

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: domaintest9
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: ' kudos.scoutflo.tech'
      http:
        paths:
          - path: /abcd
            pathType: Prefix
            backend:
              service:
                name: domaintest9
                port:
                  number: 3000
    - host: domaintest2-zp3zi.scoutflo.agency
      http:
        paths:
          - path: /abcd
            pathType: Prefix
            backend:
              service:
                name: domaintest9
                port:
                  number: 3000
  tls:
    - hosts:
        - domaintest2-zp3zi.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
