apiVersion: v1
kind: Service
metadata:
  name: dgvfscx
  namespace: scoutflo-k8sdashboard-70emx
  labels:
    app: dgvfscx
spec:
  type: ClusterIP
  selector:
    app: dgvfscx
  ports:
    - name: https
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dgvfscx
  namespace: scoutflo-k8sdashboard-70emx
  labels:
    app: dgvfscx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dgvfscx
  template:
    metadata:
      labels:
        app: dgvfscx
    spec:
      containers:
        - name: dgvfscx-container
          image: satyamp07/waitlist:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 512Mi
              cpu: 200m
            limits:
              memory: 1024Mi
              cpu: 400m
          env:
            - name: NODE_ENV
              value: production
            - name: NEXT_PUBLIC_ATLAS_BACKEND
              value: https://api.atlas.scoutflo.com/api
      imagePullSecrets:
        - name: scoutflo-satyamp07-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dgvfscx
  namespace: scoutflo-k8sdashboard-70emx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: scoutflohbn-tl5fx.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dgvfscx
                port:
                  number: 3000
  tls:
    - hosts:
        - scoutflohbn-tl5fx.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
