apiVersion: v1
kind: Service
metadata:
  name: atharvadeploytesting100
  namespace: default
  labels:
    app: atharvadeploytesting100
spec:
  type: ClusterIP
  selector:
    app: atharvadeploytesting100
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atharvadeploytesting100
  namespace: default
  labels:
    app: atharvadeploytesting100
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atharvadeploytesting100
  template:
    metadata:
      labels:
        app: atharvadeploytesting100
    spec:
      containers:
        - name: atharvadeploytesting100-container
          image: satyam/webs:agents
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 500m
          env:
            - name: NEXT_PUBLIC_ATLAS_BACKEND
              value: https://api.atlas.scoutflo.com/api
      imagePullSecrets:
        - name: scoutflo-satyam-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atharvadeploytesting100
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: test.atharva.com
      http:
        paths:
          - path: /service1
            pathType: Prefix
            backend:
              service:
                name: atharvadeploytesting100
                port:
                  number: 80
    - host: waitlist-gefiq.scoutflo.agency
      http:
        paths:
          - path: /service1
            pathType: Prefix
            backend:
              service:
                name: atharvadeploytesting100
                port:
                  number: 80
    - host: test.atharva.com
      http:
        paths:
          - path: /service2
            pathType: Prefix
            backend:
              service:
                name: atharvadeploytesting100
                port:
                  number: 443
    - host: waitlist-rlkhx.scoutflo.agency
      http:
        paths:
          - path: /service2
            pathType: Prefix
            backend:
              service:
                name: atharvadeploytesting100
                port:
                  number: 443
  tls:
    - hosts:
        - waitlist-gefiq.scoutflo.agency
        - waitlist-rlkhx.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
