apiVersion: v1
kind: Service
metadata:
  name: testab
  namespace: default
  labels:
    app: testab
spec:
  type: ClusterIP
  selector:
    app: testab
  ports:
    - name: https
      protocol: TCP
      port: 2358
      targetPort: 2358

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testab
  namespace: default
  labels:
    app: testab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testab
  template:
    metadata:
      labels:
        app: testab
    spec:
      containers:
        - name: testab-container
          image: satyamp07/judge0:latest
          ports:
            - containerPort: 2358
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 2Gi
              cpu: 1000m
          env: []
      imagePullSecrets:
        - name: scoutflo-satyam-docker-the-latest-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testab
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: judge0-test-2-iuxar.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: testab
                port:
                  number: 2358
  tls:
    - hosts:
        - judge0-test-2-iuxar.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
