apiVersion: v1
kind: Service
metadata:
  name: validchecks2
  namespace: default
  labels:
    app: validchecks2
spec:
  type: ClusterIP
  selector:
    app: validchecks2
  ports:
    - name: https
      protocol: TCP
      port: 2998
      targetPort: 2998

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validchecks2
  namespace: default
  labels:
    app: validchecks2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validchecks2
  template:
    metadata:
      labels:
        app: validchecks2
    spec:
      containers:
        - name: validchecks2-container
          image: satyam07/waitlist:latest
          ports:
            - containerPort: 2998
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 500m
          env:
            - name: NODE_ENV
              value: production
            - name: YARN_VERSION
              value: 1.22.22
      imagePullSecrets:
        - name: scoutflo-satyam-docker-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: validchecks2
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: validchecks-y5vcy.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: validchecks2
                port:
                  number: 2998
  tls:
    - hosts:
        - validchecks-y5vcy.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
