apiVersion: v1
kind: Service
metadata:
  name: dfbfdtyjtytyj
  namespace: scoutflo-monitoring
  labels:
    app: dfbfdtyjtytyj
spec:
  type: ClusterIP
  selector:
    app: dfbfdtyjtytyj
  ports:
    - name: https
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dfbfdtyjtytyj
  namespace: scoutflo-monitoring
  labels:
    app: dfbfdtyjtytyj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfbfdtyjtytyj
  template:
    metadata:
      labels:
        app: dfbfdtyjtytyj
    spec:
      containers:
        - name: dfbfdtyjtytyj-container
          image: satyamp07/waitlist:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 512Mi
              cpu: 400m
          env:
            - name: NEXT_PUBLIC_ATLAS_BACKEND
              value: https://api.atlas.scoutflo.com/api
      imagePullSecrets:
        - name: scoutflo-dockerwaitlist-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dfbfdtyjtytyj
  namespace: scoutflo-monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: test-upsert-docker-cvlyc.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dfbfdtyjtytyj
                port:
                  number: 3000
  tls:
    - hosts:
        - test-upsert-docker-cvlyc.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
