apiVersion: v1
kind: Service
metadata:
  name: atharvadeploytesting77
  namespace: default
  labels:
    app: atharvadeploytesting77
spec:
  type: ClusterIP
  selector:
    app: atharvadeploytesting77
  ports:
    - name: https
      protocol: TCP
      port: 2999
      targetPort: 2999

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atharvadeploytesting77
  namespace: default
  labels:
    app: atharvadeploytesting77
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atharvadeploytesting77
  template:
    metadata:
      labels:
        app: atharvadeploytesting77
    spec:
      containers:
        - name: atharvadeploytesting77-container
          image: satyamp07/waitlist:latest
          ports:
            - containerPort: 2999
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 500m
          env:
            - name: NODE_ENV
              value: production
            - name: NEXT_PUBLIC_ATLAS_BACKEND
              value: https://api.atlas.scoutflo.com/api
      imagePullSecrets:
        - name: scoutflo-satyam-docker-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atharvadeploytesting77
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: waitlist123-rzjdh.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: atharvadeploytesting77
                port:
                  number: 2999
  tls:
    - hosts:
        - waitlist123-rzjdh.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
