apiVersion: v1
kind: ServiceAccount
metadata:
  name: scoutflo-sa-demo-service-frtyu
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: u1HmB+p1X2Bev+KcrP3fbIuZBxWPDiyATYw0Nstt55LMJoHreh3W5+loAyDTS4vgQUSzhMzuQ/M80BF/bqXjk6y8eHEpSPxEyudc2rCmuEXsnmqqfDLooUvSDqoG6zHv
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service-frtyu
  namespace: default
  labels:
    app: demo-service-frtyu
spec:
  type: ClusterIP
  selector:
    app: demo-service-frtyu
  ports:
    - name: https
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: demo-service-frtyu-http
  namespace: default
spec:
  hosts:
  - demo-service-sds5uksnj2ir7b7p-suexwm3-dofeh.scoutflo.agency
  scaleTargetRef:
    name: demo-service-frtyu           # Deployment name
    service: demo-service-frtyu        
  minReplicas: 0
  maxReplicas: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service-frtyu
  namespace: default
  labels:
    app: demo-service-frtyu
spec:
  replicas: 0                   
  selector:
    matchLabels:
      app: demo-service-frtyu
  template:
    metadata:
      labels:
        app: demo-service-frtyu
    spec:
      serviceAccountName: scoutflo-sa-demo-service-frtyu
      containers:
      - name: demo-service-frtyu-container
        image: 296062577626.dkr.ecr.ap-south-1.amazonaws.com/welcome-scoutflo:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 500m
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        imagePullPolicy: Always
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-service-frtyu
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: demo-service-sds5uksnj2ir7b7p-suexwm3-dofeh.scoutflo.agency
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-service-frtyu
            port:
              number: 3000
  tls:
  - hosts:
    - demo-service-sds5uksnj2ir7b7p-suexwm3-dofeh.scoutflo.agency
    secretName: scoutflo-agency-wildcard-tls
