apiVersion: v1
kind: Service
metadata:
  name: adweeftrg
  namespace: dewd
  labels:
    app: adweeftrg
spec:
  type: ClusterIP
  selector:
    app: adweeftrg
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adweeftrg
  namespace: dewd
  labels:
    app: adweeftrg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adweeftrg
  template:
    metadata:
      labels:
        app: adweeftrg
    spec:
      containers:
        - name: adweeftrg-container
          image: satyamp07/waitlist:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 500m
          env: []
      imagePullSecrets:
        - name: scoutflo-satyam-docker-the-latest-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adweeftrg
  namespace: dewd
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: nmoiooio-874b6.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: adweeftrg
                port:
                  number: 80
  tls:
    - hosts:
        - nmoiooio-874b6.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
