apiVersion: v1
kind: Service
metadata:
  name: er4tbvsd
  namespace: test-cert
  labels:
    app: er4tbvsd
spec:
  type: ClusterIP
  selector:
    app: er4tbvsd
  ports:
    - name: https
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: er4tbvsd
  namespace: test-cert
  labels:
    app: er4tbvsd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: er4tbvsd
  template:
    metadata:
      labels:
        app: er4tbvsd
    spec:
      containers:
        - name: er4tbvsd-container
          image: satyamp07/waitlist:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 500m
          env:
            - name: NEXT_PUBLIC_ATLAS_BACKEND
              value: https://api.atlas.scoutflo.com/api
      imagePullSecrets:
        - name: scoutflo-satyam-docker-the-latest-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: er4tbvsd
  namespace: test-cert
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: nuteivbeurv.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: er4tbvsd
                port:
                  number: 3000
    - host: dont-wait-list-sqzqz.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: er4tbvsd
                port:
                  number: 3000
  tls:
    - hosts:
        - dont-wait-list-sqzqz.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
